services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__HTTP__HOST=0.0.0.0

  mysql:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: logs_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  qdrant_data:
  mysql_data: