services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    command: ["./qdrant", "--storage-snapshot", "/qdrant/snapshots/full-snapshot-2025-08-02-21-54-03.snapshot","--force-snapshot"]
    volumes:
      - ./snapshots:/qdrant/snapshots
    environment:
      - QDRANT__HTTP__HOST=0.0.0.0

  mysql:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: logs_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  api:
    build: .
    container_name: finance_api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - qdrant
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_NAME=logs_db
      - QDRANT_URL=http://qdrant:6333
      - DOCKER_ENV=true
    env_file:
      - .env
    command: ["uv", "run", "python", "src/app.py"]
